# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci

on:
  workflow_dispatch:
  
env:
  ACTIONS_STEP_DEBUG: true

jobs:

  android:
    runs-on: 	macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Install Gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    - name: Ndk
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r20b
        local-cache: true

    - name: Test
      run: |
        java -version
        ls -al ~/go/bin
        ls -al $ANDROID_NDK_HOME/meta
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Build
      run: |
        make android
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: |
          open_im_sdk.aar
          open_im_sdk-sources.jar

  ios:
    runs-on: 	macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Install Gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    - name: Test
      run: |
        ls -al ~/go/bin

    - name: Build
      run: |
        make ios
        tar zcvf xcframework.tar.gz build/OpenIMCore.xcframework
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios
        path: xcframework.tar.gz