# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: 	macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Install Gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    - name: Test
      run: |
        java -version
        ls -al ~/go/bin

    - name: Build
      run: make ios
      
    - name: Tar
      run: tar zcvf xcframework.tar.gz build/OpenIMCore.xcframework
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: xcframework.tar.gz
        path: xcframework.tar.gz